name: master

on:
  push:
    branches:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Build and release to pypi
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 0
          ref: master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Use poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Publish to pypi
        run: poetry publish --build --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
